name: df_dropdown
description: "This Flutter package providing versatile and customizable dropdown components with different selection modes and search functionality."

version: 1.0.0

homepage: https://dartforce.dev/
repository: https://github.com/DartForce22/df_dropdown
license: MIT

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
