name: df_dropdown
description: "This Flutter package providing versatile and customizable dropdown components with different selection modes and search functionality."

version: 1.0.2

homepage: https://dartforce.dev/
repository: https://github.com/DartForce22/df_dropdown.git
license: MIT

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2

screenshots:
  - description: "Simple Dropdown"
    path: assets/simple-dd.jpg
  - description: "Searchable Dropdown"
    path: assets/searchable-dd.jpg
  - description: "Single-Select Searchable Selector Dropdown"
    path: assets/single-select-dd.jpg
  - description: "Multi-Select Searchable Selector Dropdown"
    path: assets/multi-select-dd.jpg

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
